### ISSUE TITLE
Warning Message illegal string offset 'post-type'

### ISSUE THREAD

**Issue by tobysam** [ReversedK/LocateAnything#1]
Hello, plug in was working great, and this message below pops up on the LocateAnythingMaps options page.

"Warning: Illegal string offset 'post_type' in /home/content/n3pnexwpnas01_data02/92/3578092/html/wp-content/plugins/locateanything/admin/partials/locate-anything-settings-admin.php on line 74"

can you help me fix this?

thank you

**Comment by ReversedK** [comment]
Hello Tobysam,

I  came across this problem too on a friend's installation. Did that happen right after you updated from 1.0.0 to 1.1.x ?

Please first update to the latest version (as of now 1.1.2) then go to LocateAnything > Options, review the options to make sure they are correct and click save. It should fix the problem.
If it doesn't please contact me again.

**Comment by ReversedK** [comment]
Hey Tobysam,

After having a second look at the code there was a bug indeed. I just pushed the patched version on gitHub and will soon push it on Wordpress.org. Thanks for your feedback!

**Comment by ReversedK** [comment]
1.1.3 pushed on Wordpress.org,
 update your version, go to Options, click on any additional field text input and then click on the page, this will actualize the settings, save. The warning message  should have disappeared.

**Comment by tobysam** [comment]
Thank you for responding and helping, 

However, unfortunately I now have received this warning message:

Warning: Illegal string offset 'post_type' in /home/content/n3pnexwpnas01_data02/92/3578092/html/wp-content/plugins/locateanything/admin/partials/locate-anything-settings-admin.php on line 75

Is this due to something I have done wrong? 
Sorry for the bother, thanks for the help

**Comment by ReversedK** [comment]
Hello Tobysam,

No you haven't done anything wrong, it is probably your browser cache
Please follow exactly this process :
1. empty your cache
2. log back in to the Wordpress admin
3. go to LocateAnything > Options
4.  click on any additional field text input, let's say your create an additional field called "subtitle",  type a key, for example add an "a" (now it reads "subtitlea") and then click on the page, this will actualize the settings,
5. Delete the extra "a" you entered on step 4.
6. save. 

The warning message should have disappeared now
Please tell me if it worked.

**Comment by tobysam** [comment]
Yes great! Its gone and working again, thank you for your help!

**Comment by ReversedK** [comment]
Great, thanks again for your feedback!
