### ISSUE TITLE
Wordpress 4.8.1

### ISSUE THREAD

**Issue by andremorador** [ReversedK/LocateAnything#11]
I'm using the buddypress addon, my map loads to set up normally but does not load in the front end.

**Comment by ReversedK** [comment]
Hi Andre,
Please contact me at contact@locate-anything.com with your URL so I can have a look at your setup.
Thanks!

**Comment by andremorador** [comment]
Hello!
The maps worked with other plugins, I chose to buy this for seeming to be the best. The map has been configured without any problems, but the Front End does not load.

**Comment by andremorador** [comment]
When I use ShortCode, the page is slow, it takes time to load the page and the map does not appear. When I try to use the HTML code, the page loads normally but the map still does not appear.

**Comment by andremorador** [comment]
I did, this plugin conflicts with the Elementor.

**Comment by ReversedK** [comment]
What is the Elementor? a third party plugin?

**Comment by andremorador** [comment]
It's a widget plugin.
How I do change the color of theTooltip on the map?





Em 30 de agosto de 2017 08:46:09 -03:00, ReversedK <notifications@github.com> escreveu:

**Comment by ReversedK** [comment]
You have to style the leaflet-popup-content CSS class

**Comment by andremorador** [comment]
Hello! I have an problem with geolocation. When an user register, I need to open their profile, Geo Settings and click "Geolocate this adress", when user modify your profile, I need to do again.This should be automatic when register... Help, please.
