### ISSUE TITLE
Import from CSV

### ISSUE THREAD

**Issue by nathanyeung** [ReversedK/LocateAnything#4]
How do I import from CSV?

**Comment by ReversedK** [comment]
Hello Nathan,
Sorry for the delay, I did answer your comment right away but for some reason it doesn't appear here.

There is actually no built-in tool to import markers from CSV. It would actually be quite simple to build a simple one, it is on my todo list but I don't have the time right now. Anyone interested in helping? :)

You can use a third party plugin though. 
Inside LocateAnything markers are attached to posts. So to import from CSV you could use plugins like https://wordpress.org/plugins/csv-2-post/ that allow  to create a post with the appropriate custom fields 
 from CSV files

Hope this helps, sorry again for the delay
