### ISSUE TITLE
Buddypress Settings Not Recognising additional profile fields

### ISSUE THREAD

**Issue by WebBudd** [ReversedK/LocateAnything#7]
Hi, when trying to select the profile fields where the users geolocation information is the drop down only allows me to choose name.  I have already created several extended profile options for street, city, zipcode etc but these do not show up.  
Thanks in advance for your help.

**Comment by ReversedK** [comment]
Hello
Could you please send me access to your backoffice at
contact@locate-anything.com so I can have a look?
Thanks

**Comment by WebBudd** [comment]
Hi, 

I've sent login details to your email.  Thanks
