### ISSUE TITLE
Problem filters

### ISSUE THREAD

**Issue by dluengo1** [ReversedK/LocateAnything#8]
Good afternoon, I have problems placing the map on the right and left the filters. Could you tell me what the problem is? Thank you.

http://murillodegallegoturismo.com/servicios/
screenshot: http://prntscr.com/f69ne2

**Comment by ReversedK** [comment]
Hello
The problem is with your CSS styles. Try using the "Fullwidth" map layout, if it doesn"t work adjust your CSS manually so that the width of the map + the width of the filters block < width of their container
